In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('emp.csv')

In [3]:
df

   eno   ename
0    1  vittal
1    2  sharan

In [1]:
df

NameError: name 'df' is not defined

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('emp.csv')

In [4]:
df

     eno               ename         doj  deptno  salary
0   1001        Arjun Sharma  2022-01-15      10    1000
1   1002         Priya Patel  2023-03-22      20   67387
2   1003          Ravi Kumar  2021-05-10      30   70421
3   1004         Sneha Gupta  2020-08-25      40   68902
4   1005          Anil Reddy  2024-02-13      50   78005
5   1006          Neha Verma  2019-11-30      60   59843
6   1007         Vijay Singh  2022-07-08      10    1000
7   1008         Ananya Iyer  2021-03-15      20   74625
8   1009        Manish Joshi  2020-12-19      30   67560
9   1010         Simran Kaur  2023-01-11      40   68902
10  1011        Rajesh Mehta  2021-09-01      50   62497
11  1012       Deepika Desai  2020-06-10      60   70179
12  1013      Shivani Sharma  2022-09-13      10   74363
13  1014         Harish Nair  2023-04-01      20   61487
14  1015         Komal Yadav  2021-11-23      30   61894
15  1016          Ajay Bhatt  2020-04-25      40   70109
16  1017         Pooja Malik  2022-02-28      50   77450
17  1018        Raghav Joshi  2021-06-14      60   62873
18  1019          Meera Nair  2020-09-17      10    1000
19  1020         Krishna Rao  2023-10-02      20    2000
20  1021      Prakash Pillai  2022-12-11      10   73569
21  1022  Aishwarya Deshmukh  2021-07-25      20   69746
22  1023          Vikas Soni  2020-11-15      30   60933
23  1024          Ritu Mehra  2023-05-20      40   67801
24  1025       Nitin Chauhan  2020-03-30      50   66948
25  1026        Swati Kapoor  2021-10-05      60   66972
26  1027       Harshit Kumar  2022-08-16      10   66535
27  1028       Kanika Thakur  2020-01-10      20   67752
28  1029      Arvind Agarwal  2023-02-18      30   70986
29  1030         Divya Singh  2021-04-22      40   67845
30  1031        Akash Prasad  2020-06-05      50   72594
31  1032          Geeta Rani  2022-09-07      60   63916
32  1033         Suresh Jain  2021-12-01      10   69234
33  1034          Sonal Shah  2023-08-13      20    2000
34  1035       Jayesh Bansal  2020-02-15      30   69811
35  1036        Shweta Yadav  2021-06-03      40   63559
36  1037      Rajendra Joshi  2023-11-19      50   73561
37  1038        Kavita Mehta  2020-07-25      60   71892
38  1039          Ajit Reddy  2022-04-18      10   69399
39  1040     Pratibha Sharma  2021-09-05      20   65072
40  1041     Subodh Tripathi  2020-05-14      30   68215
41  1042        Sunita Gupta  2023-03-09      40   72534
42  1043        Arvind Kumar  2021-08-22      50   70019
43  1044      Neeraj Agarwal  2020-02-19      60   69312
44  1045        Pankaj Joshi  2022-06-10      10   70445
45  1046          Suman Iyer  2023-04-28      20   67751
46  1047         Sunil Verma  2020-09-14      30   66989
47  1048       Meenal Pandey  2021-07-03      40   66228
48  1049          Manju Nair  2022-11-17      50   69061
49  1050       Sandeep Yadav  2021-10-12      60   60921

In [8]:
df = pd.read_csv('emp.csv',usecols=['ename','salary'])

In [9]:
df

                 ename  salary
0         Arjun Sharma    1000
1          Priya Patel   67387
2           Ravi Kumar   70421
3          Sneha Gupta   68902
4           Anil Reddy   78005
5           Neha Verma   59843
6          Vijay Singh    1000
7          Ananya Iyer   74625
8         Manish Joshi   67560
9          Simran Kaur   68902
10        Rajesh Mehta   62497
11       Deepika Desai   70179
12      Shivani Sharma   74363
13         Harish Nair   61487
14         Komal Yadav   61894
15          Ajay Bhatt   70109
16         Pooja Malik   77450
17        Raghav Joshi   62873
18          Meera Nair    1000
19         Krishna Rao    2000
20      Prakash Pillai   73569
21  Aishwarya Deshmukh   69746
22          Vikas Soni   60933
23          Ritu Mehra   67801
24       Nitin Chauhan   66948
25        Swati Kapoor   66972
26       Harshit Kumar   66535
27       Kanika Thakur   67752
28      Arvind Agarwal   70986
29         Divya Singh   67845
30        Akash Prasad   72594
31          Geeta Rani   63916
32         Suresh Jain   69234
33          Sonal Shah    2000
34       Jayesh Bansal   69811
35        Shweta Yadav   63559
36      Rajendra Joshi   73561
37        Kavita Mehta   71892
38          Ajit Reddy   69399
39     Pratibha Sharma   65072
40     Subodh Tripathi   68215
41        Sunita Gupta   72534
42        Arvind Kumar   70019
43      Neeraj Agarwal   69312
44        Pankaj Joshi   70445
45          Suman Iyer   67751
46         Sunil Verma   66989
47       Meenal Pandey   66228
48          Manju Nair   69061
49       Sandeep Yadav   60921

In [10]:
df = pd.read_csv('emp.csv', index_col='eno')

In [11]:
df

                   ename         doj  deptno  salary
eno
1001        Arjun Sharma  2022-01-15      10    1000
1002         Priya Patel  2023-03-22      20   67387
1003          Ravi Kumar  2021-05-10      30   70421
1004         Sneha Gupta  2020-08-25      40   68902
1005          Anil Reddy  2024-02-13      50   78005
1006          Neha Verma  2019-11-30      60   59843
1007         Vijay Singh  2022-07-08      10    1000
1008         Ananya Iyer  2021-03-15      20   74625
1009        Manish Joshi  2020-12-19      30   67560
1010         Simran Kaur  2023-01-11      40   68902
1011        Rajesh Mehta  2021-09-01      50   62497
1012       Deepika Desai  2020-06-10      60   70179
1013      Shivani Sharma  2022-09-13      10   74363
1014         Harish Nair  2023-04-01      20   61487
1015         Komal Yadav  2021-11-23      30   61894
1016          Ajay Bhatt  2020-04-25      40   70109
1017         Pooja Malik  2022-02-28      50   77450
1018        Raghav Joshi  2021-06-14      60   62873
1019          Meera Nair  2020-09-17      10    1000
1020         Krishna Rao  2023-10-02      20    2000
1021      Prakash Pillai  2022-12-11      10   73569
1022  Aishwarya Deshmukh  2021-07-25      20   69746
1023          Vikas Soni  2020-11-15      30   60933
1024          Ritu Mehra  2023-05-20      40   67801
1025       Nitin Chauhan  2020-03-30      50   66948
1026        Swati Kapoor  2021-10-05      60   66972
1027       Harshit Kumar  2022-08-16      10   66535
1028       Kanika Thakur  2020-01-10      20   67752
1029      Arvind Agarwal  2023-02-18      30   70986
1030         Divya Singh  2021-04-22      40   67845
1031        Akash Prasad  2020-06-05      50   72594
1032          Geeta Rani  2022-09-07      60   63916
1033         Suresh Jain  2021-12-01      10   69234
1034          Sonal Shah  2023-08-13      20    2000
1035       Jayesh Bansal  2020-02-15      30   69811
1036        Shweta Yadav  2021-06-03      40   63559
1037      Rajendra Joshi  2023-11-19      50   73561
1038        Kavita Mehta  2020-07-25      60   71892
1039          Ajit Reddy  2022-04-18      10   69399
1040     Pratibha Sharma  2021-09-05      20   65072
1041     Subodh Tripathi  2020-05-14      30   68215
1042        Sunita Gupta  2023-03-09      40   72534
1043        Arvind Kumar  2021-08-22      50   70019
1044      Neeraj Agarwal  2020-02-19      60   69312
1045        Pankaj Joshi  2022-06-10      10   70445
1046          Suman Iyer  2023-04-28      20   67751
1047         Sunil Verma  2020-09-14      30   66989
1048       Meenal Pandey  2021-07-03      40   66228
1049          Manju Nair  2022-11-17      50   69061
1050       Sandeep Yadav  2021-10-12      60   60921

In [12]:
df = pd.read_csv('emp.csv', skiprows=10)

In [13]:
df

    1010         Simran Kaur  2023-01-11  40  68902
0   1011        Rajesh Mehta  2021-09-01  50  62497
1   1012       Deepika Desai  2020-06-10  60  70179
2   1013      Shivani Sharma  2022-09-13  10  74363
3   1014         Harish Nair  2023-04-01  20  61487
4   1015         Komal Yadav  2021-11-23  30  61894
5   1016          Ajay Bhatt  2020-04-25  40  70109
6   1017         Pooja Malik  2022-02-28  50  77450
7   1018        Raghav Joshi  2021-06-14  60  62873
8   1019          Meera Nair  2020-09-17  10   1000
9   1020         Krishna Rao  2023-10-02  20   2000
10  1021      Prakash Pillai  2022-12-11  10  73569
11  1022  Aishwarya Deshmukh  2021-07-25  20  69746
12  1023          Vikas Soni  2020-11-15  30  60933
13  1024          Ritu Mehra  2023-05-20  40  67801
14  1025       Nitin Chauhan  2020-03-30  50  66948
15  1026        Swati Kapoor  2021-10-05  60  66972
16  1027       Harshit Kumar  2022-08-16  10  66535
17  1028       Kanika Thakur  2020-01-10  20  67752
18  1029      Arvind Agarwal  2023-02-18  30  70986
19  1030         Divya Singh  2021-04-22  40  67845
20  1031        Akash Prasad  2020-06-05  50  72594
21  1032          Geeta Rani  2022-09-07  60  63916
22  1033         Suresh Jain  2021-12-01  10  69234
23  1034          Sonal Shah  2023-08-13  20   2000
24  1035       Jayesh Bansal  2020-02-15  30  69811
25  1036        Shweta Yadav  2021-06-03  40  63559
26  1037      Rajendra Joshi  2023-11-19  50  73561
27  1038        Kavita Mehta  2020-07-25  60  71892
28  1039          Ajit Reddy  2022-04-18  10  69399
29  1040     Pratibha Sharma  2021-09-05  20  65072
30  1041     Subodh Tripathi  2020-05-14  30  68215
31  1042        Sunita Gupta  2023-03-09  40  72534
32  1043        Arvind Kumar  2021-08-22  50  70019
33  1044      Neeraj Agarwal  2020-02-19  60  69312
34  1045        Pankaj Joshi  2022-06-10  10  70445
35  1046          Suman Iyer  2023-04-28  20  67751
36  1047         Sunil Verma  2020-09-14  30  66989
37  1048       Meenal Pandey  2021-07-03  40  66228
38  1049          Manju Nair  2022-11-17  50  69061
39  1050       Sandeep Yadav  2021-10-12  60  60921

In [14]:
 df = pd.read_csv('emp.csv', skiprows=10, nrows=10)

In [15]:
df

   1010     Simran Kaur  2023-01-11  40  68902
0  1011    Rajesh Mehta  2021-09-01  50  62497
1  1012   Deepika Desai  2020-06-10  60  70179
2  1013  Shivani Sharma  2022-09-13  10  74363
3  1014     Harish Nair  2023-04-01  20  61487
4  1015     Komal Yadav  2021-11-23  30  61894
5  1016      Ajay Bhatt  2020-04-25  40  70109
6  1017     Pooja Malik  2022-02-28  50  77450
7  1018    Raghav Joshi  2021-06-14  60  62873
8  1019      Meera Nair  2020-09-17  10   1000
9  1020     Krishna Rao  2023-10-02  20   2000

In [16]:
df = pd.read_csv('emp.csv',parse_dates=['doj'])

In [17]:
df

     eno               ename        doj  deptno  salary
0   1001        Arjun Sharma 2022-01-15      10    1000
1   1002         Priya Patel 2023-03-22      20   67387
2   1003          Ravi Kumar 2021-05-10      30   70421
3   1004         Sneha Gupta 2020-08-25      40   68902
4   1005          Anil Reddy 2024-02-13      50   78005
5   1006          Neha Verma 2019-11-30      60   59843
6   1007         Vijay Singh 2022-07-08      10    1000
7   1008         Ananya Iyer 2021-03-15      20   74625
8   1009        Manish Joshi 2020-12-19      30   67560
9   1010         Simran Kaur 2023-01-11      40   68902
10  1011        Rajesh Mehta 2021-09-01      50   62497
11  1012       Deepika Desai 2020-06-10      60   70179
12  1013      Shivani Sharma 2022-09-13      10   74363
13  1014         Harish Nair 2023-04-01      20   61487
14  1015         Komal Yadav 2021-11-23      30   61894
15  1016          Ajay Bhatt 2020-04-25      40   70109
16  1017         Pooja Malik 2022-02-28      50   77450
17  1018        Raghav Joshi 2021-06-14      60   62873
18  1019          Meera Nair 2020-09-17      10    1000
19  1020         Krishna Rao 2023-10-02      20    2000
20  1021      Prakash Pillai 2022-12-11      10   73569
21  1022  Aishwarya Deshmukh 2021-07-25      20   69746
22  1023          Vikas Soni 2020-11-15      30   60933
23  1024          Ritu Mehra 2023-05-20      40   67801
24  1025       Nitin Chauhan 2020-03-30      50   66948
25  1026        Swati Kapoor 2021-10-05      60   66972
26  1027       Harshit Kumar 2022-08-16      10   66535
27  1028       Kanika Thakur 2020-01-10      20   67752
28  1029      Arvind Agarwal 2023-02-18      30   70986
29  1030         Divya Singh 2021-04-22      40   67845
30  1031        Akash Prasad 2020-06-05      50   72594
31  1032          Geeta Rani 2022-09-07      60   63916
32  1033         Suresh Jain 2021-12-01      10   69234
33  1034          Sonal Shah 2023-08-13      20    2000
34  1035       Jayesh Bansal 2020-02-15      30   69811
35  1036        Shweta Yadav 2021-06-03      40   63559
36  1037      Rajendra Joshi 2023-11-19      50   73561
37  1038        Kavita Mehta 2020-07-25      60   71892
38  1039          Ajit Reddy 2022-04-18      10   69399
39  1040     Pratibha Sharma 2021-09-05      20   65072
40  1041     Subodh Tripathi 2020-05-14      30   68215
41  1042        Sunita Gupta 2023-03-09      40   72534
42  1043        Arvind Kumar 2021-08-22      50   70019
43  1044      Neeraj Agarwal 2020-02-19      60   69312
44  1045        Pankaj Joshi 2022-06-10      10   70445
45  1046          Suman Iyer 2023-04-28      20   67751
46  1047         Sunil Verma 2020-09-14      30   66989
47  1048       Meenal Pandey 2021-07-03      40   66228
48  1049          Manju Nair 2022-11-17      50   69061
49  1050       Sandeep Yadav 2021-10-12      60   60921

In [18]:
df['doj'] = df['doj'].dt.strftime('%d-%m-%Y')

In [19]:
df

     eno               ename         doj  deptno  salary
0   1001        Arjun Sharma  15-01-2022      10    1000
1   1002         Priya Patel  22-03-2023      20   67387
2   1003          Ravi Kumar  10-05-2021      30   70421
3   1004         Sneha Gupta  25-08-2020      40   68902
4   1005          Anil Reddy  13-02-2024      50   78005
5   1006          Neha Verma  30-11-2019      60   59843
6   1007         Vijay Singh  08-07-2022      10    1000
7   1008         Ananya Iyer  15-03-2021      20   74625
8   1009        Manish Joshi  19-12-2020      30   67560
9   1010         Simran Kaur  11-01-2023      40   68902
10  1011        Rajesh Mehta  01-09-2021      50   62497
11  1012       Deepika Desai  10-06-2020      60   70179
12  1013      Shivani Sharma  13-09-2022      10   74363
13  1014         Harish Nair  01-04-2023      20   61487
14  1015         Komal Yadav  23-11-2021      30   61894
15  1016          Ajay Bhatt  25-04-2020      40   70109
16  1017         Pooja Malik  28-02-2022      50   77450
17  1018        Raghav Joshi  14-06-2021      60   62873
18  1019          Meera Nair  17-09-2020      10    1000
19  1020         Krishna Rao  02-10-2023      20    2000
20  1021      Prakash Pillai  11-12-2022      10   73569
21  1022  Aishwarya Deshmukh  25-07-2021      20   69746
22  1023          Vikas Soni  15-11-2020      30   60933
23  1024          Ritu Mehra  20-05-2023      40   67801
24  1025       Nitin Chauhan  30-03-2020      50   66948
25  1026        Swati Kapoor  05-10-2021      60   66972
26  1027       Harshit Kumar  16-08-2022      10   66535
27  1028       Kanika Thakur  10-01-2020      20   67752
28  1029      Arvind Agarwal  18-02-2023      30   70986
29  1030         Divya Singh  22-04-2021      40   67845
30  1031        Akash Prasad  05-06-2020      50   72594
31  1032          Geeta Rani  07-09-2022      60   63916
32  1033         Suresh Jain  01-12-2021      10   69234
33  1034          Sonal Shah  13-08-2023      20    2000
34  1035       Jayesh Bansal  15-02-2020      30   69811
35  1036        Shweta Yadav  03-06-2021      40   63559
36  1037      Rajendra Joshi  19-11-2023      50   73561
37  1038        Kavita Mehta  25-07-2020      60   71892
38  1039          Ajit Reddy  18-04-2022      10   69399
39  1040     Pratibha Sharma  05-09-2021      20   65072
40  1041     Subodh Tripathi  14-05-2020      30   68215
41  1042        Sunita Gupta  09-03-2023      40   72534
42  1043        Arvind Kumar  22-08-2021      50   70019
43  1044      Neeraj Agarwal  19-02-2020      60   69312
44  1045        Pankaj Joshi  10-06-2022      10   70445
45  1046          Suman Iyer  28-04-2023      20   67751
46  1047         Sunil Verma  14-09-2020      30   66989
47  1048       Meenal Pandey  03-07-2021      40   66228
48  1049          Manju Nair  17-11-2022      50   69061
49  1050       Sandeep Yadav  12-10-2021      60   60921

In [20]:
df['doj']

0     15-01-2022
1     22-03-2023
2     10-05-2021
3     25-08-2020
4     13-02-2024
5     30-11-2019
6     08-07-2022
7     15-03-2021
8     19-12-2020
9     11-01-2023
10    01-09-2021
11    10-06-2020
12    13-09-2022
13    01-04-2023
14    23-11-2021
15    25-04-2020
16    28-02-2022
17    14-06-2021
18    17-09-2020
19    02-10-2023
20    11-12-2022
21    25-07-2021
22    15-11-2020
23    20-05-2023
24    30-03-2020
25    05-10-2021
26    16-08-2022
27    10-01-2020
28    18-02-2023
29    22-04-2021
30    05-06-2020
31    07-09-2022
32    01-12-2021
33    13-08-2023
34    15-02-2020
35    03-06-2021
36    19-11-2023
37    25-07-2020
38    18-04-2022
39    05-09-2021
40    14-05-2020
41    09-03-2023
42    22-08-2021
43    19-02-2020
44    10-06-2022
45    28-04-2023
46    14-09-2020
47    03-07-2021
48    17-11-2022
49    12-10-2021
Name: doj, dtype: object

In [34]:
import pandas as pd

In [35]:
data = {'A': [2, 1, 3], 'B': [5, 6, 7]}

In [36]:
df = pd.DataFrame(data)

In [31]:
 df_sorted = df.sort_values(by='B')

In [37]:
df_sorted

   A  B
0  2  5
1  1  6
2  3  7

In [38]:
 import pandas as pd

In [40]:
 data = {'A': [2, 1, 3], 'B': [5, 6, 7]}

In [41]:
 df = pd.DataFrame(data, index=[2, 1, 3])

SyntaxError: invalid non-printable character U+2006 (1048778134.py, line 1)

In [42]:
import pandas as pd

In [43]:
data = {'Category': ['A', 'B', 'A', 'B', 'A'],
'Values': [10, 20, 30, 40, 50]}

In [44]:
df = pd.DataFrame(data)

In [45]:
df

  Category  Values
0        A      10
1        B      20
2        A      30
3        B      40
4        A      50

In [46]:
grouped = df.groupby('Category')['Values'].sum()

In [47]:
grouped

Category
A    90
B    60
Name: Values, dtype: int64

In [48]:
df

  Category  Values
0        A      10
1        B      20
2        A      30
3        B      40
4        A      50

In [49]:
import pd as pandas

ModuleNotFoundError: No module named 'pd'

In [50]:
import pandas as pd

In [51]:
df = pd.read_csv('emp.csv')

In [52]:
df

     eno               ename         doj  deptno  salary
0   1001        Arjun Sharma  2022-01-15      10    1000
1   1002         Priya Patel  2023-03-22      20   67387
2   1003          Ravi Kumar  2021-05-10      30   70421
3   1004         Sneha Gupta  2020-08-25      40   68902
4   1005          Anil Reddy  2024-02-13      50   78005
5   1006          Neha Verma  2019-11-30      60   59843
6   1007         Vijay Singh  2022-07-08      10    1000
7   1008         Ananya Iyer  2021-03-15      20   74625
8   1009        Manish Joshi  2020-12-19      30   67560
9   1010         Simran Kaur  2023-01-11      40   68902
10  1011        Rajesh Mehta  2021-09-01      50   62497
11  1012       Deepika Desai  2020-06-10      60   70179
12  1013      Shivani Sharma  2022-09-13      10   74363
13  1014         Harish Nair  2023-04-01      20   61487
14  1015         Komal Yadav  2021-11-23      30   61894
15  1016          Ajay Bhatt  2020-04-25      40   70109
16  1017         Pooja Malik  2022-02-28      50   77450
17  1018        Raghav Joshi  2021-06-14      60   62873
18  1019          Meera Nair  2020-09-17      10    1000
19  1020         Krishna Rao  2023-10-02      20    2000
20  1021      Prakash Pillai  2022-12-11      10   73569
21  1022  Aishwarya Deshmukh  2021-07-25      20   69746
22  1023          Vikas Soni  2020-11-15      30   60933
23  1024          Ritu Mehra  2023-05-20      40   67801
24  1025       Nitin Chauhan  2020-03-30      50   66948
25  1026        Swati Kapoor  2021-10-05      60   66972
26  1027       Harshit Kumar  2022-08-16      10   66535
27  1028       Kanika Thakur  2020-01-10      20   67752
28  1029      Arvind Agarwal  2023-02-18      30   70986
29  1030         Divya Singh  2021-04-22      40   67845
30  1031        Akash Prasad  2020-06-05      50   72594
31  1032          Geeta Rani  2022-09-07      60   63916
32  1033         Suresh Jain  2021-12-01      10   69234
33  1034          Sonal Shah  2023-08-13      20    2000
34  1035       Jayesh Bansal  2020-02-15      30   69811
35  1036        Shweta Yadav  2021-06-03      40   63559
36  1037      Rajendra Joshi  2023-11-19      50   73561
37  1038        Kavita Mehta  2020-07-25      60   71892
38  1039          Ajit Reddy  2022-04-18      10   69399
39  1040     Pratibha Sharma  2021-09-05      20   65072
40  1041     Subodh Tripathi  2020-05-14      30   68215
41  1042        Sunita Gupta  2023-03-09      40   72534
42  1043        Arvind Kumar  2021-08-22      50   70019
43  1044      Neeraj Agarwal  2020-02-19      60   69312
44  1045        Pankaj Joshi  2022-06-10      10   70445
45  1046          Suman Iyer  2023-04-28      20   67751
46  1047         Sunil Verma  2020-09-14      30   66989
47  1048       Meenal Pandey  2021-07-03      40   66228
48  1049          Manju Nair  2022-11-17      50   69061
49  1050       Sandeep Yadav  2021-10-12      60   60921

In [53]:
filtered_df = df[df['salary'] < 10000]

In [54]:
filtered_df

     eno         ename         doj  deptno  salary
0   1001  Arjun Sharma  2022-01-15      10    1000
6   1007   Vijay Singh  2022-07-08      10    1000
18  1019    Meera Nair  2020-09-17      10    1000
19  1020   Krishna Rao  2023-10-02      20    2000
33  1034    Sonal Shah  2023-08-13      20    2000

In [55]:
total_saalries_by_deptno_salLessThan10000 = filtered_df.groupby('deptno')
['salary'].sum().reset_index()

AttributeError: 'list' object has no attribute 'sum'

In [56]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   eno     50 non-null     int64
 1   ename   50 non-null     object
 2   doj     50 non-null     object
 3   deptno  50 non-null     int64
 4   salary  50 non-null     int64
dtypes: int64(3), object(2)
memory usage: 2.1+ KB

              eno     deptno        salary
count    50.00000  50.000000     50.000000
mean   1025.50000  34.200000  61661.940000
std      14.57738  17.389887  20686.385756
min    1001.00000  10.000000   1000.000000
25%    1013.25000  20.000000  63648.250000
50%    1025.50000  30.000000  67823.000000
75%    1037.75000  50.000000  70161.500000
max    1050.00000  60.000000  78005.000000

In [57]:
df

     eno               ename         doj  deptno  salary
0   1001        Arjun Sharma  2022-01-15      10    1000
1   1002         Priya Patel  2023-03-22      20   67387
2   1003          Ravi Kumar  2021-05-10      30   70421
3   1004         Sneha Gupta  2020-08-25      40   68902
4   1005          Anil Reddy  2024-02-13      50   78005
5   1006          Neha Verma  2019-11-30      60   59843
6   1007         Vijay Singh  2022-07-08      10    1000
7   1008         Ananya Iyer  2021-03-15      20   74625
8   1009        Manish Joshi  2020-12-19      30   67560
9   1010         Simran Kaur  2023-01-11      40   68902
10  1011        Rajesh Mehta  2021-09-01      50   62497
11  1012       Deepika Desai  2020-06-10      60   70179
12  1013      Shivani Sharma  2022-09-13      10   74363
13  1014         Harish Nair  2023-04-01      20   61487
14  1015         Komal Yadav  2021-11-23      30   61894
15  1016          Ajay Bhatt  2020-04-25      40   70109
16  1017         Pooja Malik  2022-02-28      50   77450
17  1018        Raghav Joshi  2021-06-14      60   62873
18  1019          Meera Nair  2020-09-17      10    1000
19  1020         Krishna Rao  2023-10-02      20    2000
20  1021      Prakash Pillai  2022-12-11      10   73569
21  1022  Aishwarya Deshmukh  2021-07-25      20   69746
22  1023          Vikas Soni  2020-11-15      30   60933
23  1024          Ritu Mehra  2023-05-20      40   67801
24  1025       Nitin Chauhan  2020-03-30      50   66948
25  1026        Swati Kapoor  2021-10-05      60   66972
26  1027       Harshit Kumar  2022-08-16      10   66535
27  1028       Kanika Thakur  2020-01-10      20   67752
28  1029      Arvind Agarwal  2023-02-18      30   70986
29  1030         Divya Singh  2021-04-22      40   67845
30  1031        Akash Prasad  2020-06-05      50   72594
31  1032          Geeta Rani  2022-09-07      60   63916
32  1033         Suresh Jain  2021-12-01      10   69234
33  1034          Sonal Shah  2023-08-13      20    2000
34  1035       Jayesh Bansal  2020-02-15      30   69811
35  1036        Shweta Yadav  2021-06-03      40   63559
36  1037      Rajendra Joshi  2023-11-19      50   73561
37  1038        Kavita Mehta  2020-07-25      60   71892
38  1039          Ajit Reddy  2022-04-18      10   69399
39  1040     Pratibha Sharma  2021-09-05      20   65072
40  1041     Subodh Tripathi  2020-05-14      30   68215
41  1042        Sunita Gupta  2023-03-09      40   72534
42  1043        Arvind Kumar  2021-08-22      50   70019
43  1044      Neeraj Agarwal  2020-02-19      60   69312
44  1045        Pankaj Joshi  2022-06-10      10   70445
45  1046          Suman Iyer  2023-04-28      20   67751
46  1047         Sunil Verma  2020-09-14      30   66989
47  1048       Meenal Pandey  2021-07-03      40   66228
48  1049          Manju Nair  2022-11-17      50   69061
49  1050       Sandeep Yadav  2021-10-12      60   60921

In [58]:
result = df.groupby('deptno').agg(
    total_emp=('salary','count'),
    min_salary=('salary','min'),
    max_salary=('salary','max'),
    total_salary=('salary','sum')
)

In [59]:
result

        total_emp  min_salary  max_salary  total_salary
deptno
10              9        1000       74363        426545
20              9        2000       74625        477820
30              8       60933       70986        536809
40              8       63559       72534        545880
50              8       62497       78005        570135
60              8       59843       71892        525908

In [60]:
result = df.groupby(['deptno','salary'])['salary'].agg(['count','min','max','sum'])

In [61]:
result

               count    min    max     sum
deptno salary
10     1000        3   1000   1000    3000
       66535       1  66535  66535   66535
       69234       1  69234  69234   69234
       69399       1  69399  69399   69399
       70445       1  70445  70445   70445
       73569       1  73569  73569   73569
       74363       1  74363  74363   74363
20     2000        2   2000   2000    4000
       61487       1  61487  61487   61487
       65072       1  65072  65072   65072
       67387       1  67387  67387   67387
       67751       1  67751  67751   67751
       67752       1  67752  67752   67752
       69746       1  69746  69746   69746
       74625       1  74625  74625   74625
30     60933       1  60933  60933   60933
       61894       1  61894  61894   61894
       66989       1  66989  66989   66989
       67560       1  67560  67560   67560
       68215       1  68215  68215   68215
       69811       1  69811  69811   69811
       70421       1  70421  70421   70421
       70986       1  70986  70986   70986
40     63559       1  63559  63559   63559
       66228       1  66228  66228   66228
       67801       1  67801  67801   67801
       67845       1  67845  67845   67845
       68902       2  68902  68902  137804
       70109       1  70109  70109   70109
       72534       1  72534  72534   72534
50     62497       1  62497  62497   62497
       66948       1  66948  66948   66948
       69061       1  69061  69061   69061
       70019       1  70019  70019   70019
       72594       1  72594  72594   72594
       73561       1  73561  73561   73561
       77450       1  77450  77450   77450
       78005       1  78005  78005   78005
60     59843       1  59843  59843   59843
       60921       1  60921  60921   60921
       62873       1  62873  62873   62873
       63916       1  63916  63916   63916
       66972       1  66972  66972   66972
       69312       1  69312  69312   69312
       70179       1  70179  70179   70179
       71892       1  71892  71892   71892

In [62]:
result = df[df['deptno'].isin([10,20])]

In [63]:
result

     eno               ename         doj  deptno  salary
0   1001        Arjun Sharma  2022-01-15      10    1000
1   1002         Priya Patel  2023-03-22      20   67387
6   1007         Vijay Singh  2022-07-08      10    1000
7   1008         Ananya Iyer  2021-03-15      20   74625
12  1013      Shivani Sharma  2022-09-13      10   74363
13  1014         Harish Nair  2023-04-01      20   61487
18  1019          Meera Nair  2020-09-17      10    1000
19  1020         Krishna Rao  2023-10-02      20    2000
20  1021      Prakash Pillai  2022-12-11      10   73569
21  1022  Aishwarya Deshmukh  2021-07-25      20   69746
26  1027       Harshit Kumar  2022-08-16      10   66535
27  1028       Kanika Thakur  2020-01-10      20   67752
32  1033         Suresh Jain  2021-12-01      10   69234
33  1034          Sonal Shah  2023-08-13      20    2000
38  1039          Ajit Reddy  2022-04-18      10   69399
39  1040     Pratibha Sharma  2021-09-05      20   65072
44  1045        Pankaj Joshi  2022-06-10      10   70445
45  1046          Suman Iyer  2023-04-28      20   67751

In [65]:
import pandas as pd

In [66]:
df = pd.read_csv("emp.csv")

In [67]:
df

     eno               ename         doj  deptno  salary
0   1001        Arjun Sharma  2022-01-15      10    1000
1   1002         Priya Patel  2023-03-22      20   67387
2   1003          Ravi Kumar  2021-05-10      30   70421
3   1004         Sneha Gupta  2020-08-25      40   68902
4   1005          Anil Reddy  2024-02-13      50   78005
5   1006          Neha Verma  2019-11-30      60   59843
6   1007         Vijay Singh  2022-07-08      10    1000
7   1008         Ananya Iyer  2021-03-15      20   74625
8   1009        Manish Joshi  2020-12-19      30   67560
9   1010         Simran Kaur  2023-01-11      40   68902
10  1011        Rajesh Mehta  2021-09-01      50   62497
11  1012       Deepika Desai  2020-06-10      60   70179
12  1013      Shivani Sharma  2022-09-13      10   74363
13  1014         Harish Nair  2023-04-01      20   61487
14  1015         Komal Yadav  2021-11-23      30   61894
15  1016          Ajay Bhatt  2020-04-25      40   70109
16  1017         Pooja Malik  2022-02-28      50   77450
17  1018        Raghav Joshi  2021-06-14      60   62873
18  1019          Meera Nair  2020-09-17      10    1000
19  1020         Krishna Rao  2023-10-02      20    2000
20  1021      Prakash Pillai  2022-12-11      10   73569
21  1022  Aishwarya Deshmukh  2021-07-25      20   69746
22  1023          Vikas Soni  2020-11-15      30   60933
23  1024          Ritu Mehra  2023-05-20      40   67801
24  1025       Nitin Chauhan  2020-03-30      50   66948
25  1026        Swati Kapoor  2021-10-05      60   66972
26  1027       Harshit Kumar  2022-08-16      10   66535
27  1028       Kanika Thakur  2020-01-10      20   67752
28  1029      Arvind Agarwal  2023-02-18      30   70986
29  1030         Divya Singh  2021-04-22      40   67845
30  1031        Akash Prasad  2020-06-05      50   72594
31  1032          Geeta Rani  2022-09-07      60   63916
32  1033         Suresh Jain  2021-12-01      10   69234
33  1034          Sonal Shah  2023-08-13      20    2000
34  1035       Jayesh Bansal  2020-02-15      30   69811
35  1036        Shweta Yadav  2021-06-03      40   63559
36  1037      Rajendra Joshi  2023-11-19      50   73561
37  1038        Kavita Mehta  2020-07-25      60   71892
38  1039          Ajit Reddy  2022-04-18      10   69399
39  1040     Pratibha Sharma  2021-09-05      20   65072
40  1041     Subodh Tripathi  2020-05-14      30   68215
41  1042        Sunita Gupta  2023-03-09      40   72534
42  1043        Arvind Kumar  2021-08-22      50   70019
43  1044      Neeraj Agarwal  2020-02-19      60   69312
44  1045        Pankaj Joshi  2022-06-10      10   70445
45  1046          Suman Iyer  2023-04-28      20   67751
46  1047         Sunil Verma  2020-09-14      30   66989
47  1048       Meenal Pandey  2021-07-03      40   66228
48  1049          Manju Nair  2022-11-17      50   69061
49  1050       Sandeep Yadav  2021-10-12      60   60921

In [68]:
result_df = df[df.duplicated(keep=False)]

print(result_df)

Empty DataFrame
Columns: [eno, ename, doj, deptno, salary]
Index: []