In [13]:
from sqlalchemy import create_engine
import pandas as pd

oracle_connection = create_engine( "oracle+cx_oracle://sys:Admin@localhost:1521/orcl?mode=SYSDBA")
sql_query = """select *from emp"""
df = pd.read_sql(sql_query,oracle_connection)

In [14]:
df

    empno   ename        job     mgr   hiredate     sal    comm  deptno
0    7839    KING  PRESIDENT     NaN 1981-11-17  5000.0     NaN      10
1    7698   BLAKE    MANAGER  7839.0 1981-05-01  2850.0     NaN      30
2    7782   CLARK    MANAGER  7839.0 1981-06-09  2450.0     NaN      10
3    7566   JONES    MANAGER  7839.0 1981-04-02  2975.0     NaN      20
4    7788   SCOTT    ANALYST  7566.0 1987-04-19  3000.0     NaN      20
5    7902    FORD    ANALYST  7566.0 1981-12-03  3000.0     NaN      20
6    7369   SMITH      CLERK  7902.0 1980-12-17   800.0     NaN      20
7    7499   ALLEN   SALESMAN  7698.0 1981-02-20  1600.0   300.0      30
8    7521    WARD   SALESMAN  7698.0 1981-02-22  1250.0   500.0      30
9    7654  MARTIN   SALESMAN  7698.0 1981-09-28  1250.0  1400.0      30
10   7844  TURNER   SALESMAN  7698.0 1981-09-08  1500.0     0.0      30
11   7876   ADAMS      CLERK  7788.0 1987-05-23  1100.0     NaN      20
12   7900   JAMES      CLERK  7698.0 1981-12-03   950.0     NaN      30
13   7934  MILLER      CLERK  7782.0 1982-01-23  1300.0     NaN      10

In [1]:
import pandas as pd

In [2]:
 data = {'Category': ['A', 'B', 'A', 'B', 'A'],
 'Values': [10, 20, 30, 40, 50]}

In [3]:
data

{'Category': ['A', 'B', 'A', 'B', 'A'], 'Values': [10, 20, 30, 40, 50]}

In [4]:
df = pd.DataFrame(data)

In [5]:
df

  Category  Values
0        A      10
1        B      20
2        A      30
3        B      40
4        A      50

In [6]:
 grouped = df.groupby('Category')['Values'].sum()

In [7]:
print(grouped)

Category
A    90
B    60
Name: Values, dtype: int64

In [8]:
 import pandas as pd

In [9]:
 data = {'Category': ['A', 'B', 'A', 'B', 'A'],
 'Type': ['X', 'X', 'Y', 'Y', 'Y'],
 'Values': [10, 20, 30, 40, 50]}

In [10]:
 df = pd.DataFrame(data)

In [11]:
df

  Category Type  Values
0        A    X      10
1        B    X      20
2        A    Y      30
3        B    Y      40
4        A    Y      50

In [12]:
grouped = df.groupby('Category','type')['Values'].sum()

ValueError: No axis named type for object type DataFrame

In [13]:
 grouped = df.groupby(['Category', 'Type'])['Values'].sum()

In [14]:
grouped

Category  Type
A         X       10
          Y       80
B         X       20
          Y       40
Name: Values, dtype: int64

In [15]:
import pandas as pd

In [16]:
 data = {'Category': ['A', 'B', 'A', 'B', 'A'],
 'Values': [10, 20, 30, 40, 50]}

In [17]:
 df = pd.DataFrame(data)

In [18]:
df

  Category  Values
0        A      10
1        B      20
2        A      30
3        B      40
4        A      50

In [19]:
 grouped = df.groupby('Category')['Values'].agg(['sum', 'mean'])

In [20]:
grouped

          sum  mean
Category
A          90  30.0
B          60  30.0

In [21]:
from sqlalchemy import create_engine
import pandas as pd

oracle_connection = create_engine( "oracle+cx_oracle://sys:Admin@localhost:1521/orcl?mode=SYSDBA")
sql_query = """select *from emp"""
df = pd.read_sql(sql_query,oracle_connection)

In [22]:
df

    empno   ename        job     mgr   hiredate     sal    comm  deptno
0    7839    KING  PRESIDENT     NaN 1981-11-17  5000.0     NaN      10
1    7698   BLAKE    MANAGER  7839.0 1981-05-01  2850.0     NaN      30
2    7782   CLARK    MANAGER  7839.0 1981-06-09  2450.0     NaN      10
3    7566   JONES    MANAGER  7839.0 1981-04-02  2975.0     NaN      20
4    7788   SCOTT    ANALYST  7566.0 1987-04-19  3000.0     NaN      20
5    7902    FORD    ANALYST  7566.0 1981-12-03  3000.0     NaN      20
6    7369   SMITH      CLERK  7902.0 1980-12-17   800.0     NaN      20
7    7499   ALLEN   SALESMAN  7698.0 1981-02-20  1600.0   300.0      30
8    7521    WARD   SALESMAN  7698.0 1981-02-22  1250.0   500.0      30
9    7654  MARTIN   SALESMAN  7698.0 1981-09-28  1250.0  1400.0      30
10   7844  TURNER   SALESMAN  7698.0 1981-09-08  1500.0     0.0      30
11   7876   ADAMS      CLERK  7788.0 1987-05-23  1100.0     NaN      20
12   7900   JAMES      CLERK  7698.0 1981-12-03   950.0     NaN      30
13   7934  MILLER      CLERK  7782.0 1982-01-23  1300.0     NaN      10

In [25]:
   df_agg = df.groupby(['deptno','salary'])['salary'].agg(['sum','max','min','count'])

KeyError: 'salary'

In [26]:
import pandas as pd

In [27]:
df = pd.read_csv("emp.csv")

In [28]:
df

      eno    ename  salary  deptno         doj
0      10    Amber    1000      10  2018-05-14
1       2     Amar    1000      10  2017-03-22
2       8    Sagar    1000      20  2020-11-30
3       4   Thomas    1000      10  2019-08-18
4       5     Jade    2000      10  2021-02-10
5       6    Smith    1000      10  2016-12-01
6       7   Robert    3000      20  2023-06-25
7       3     Nick    1000      30  2015-09-15
8       9    Naman    4000      30  2020-01-20
9       1    Vikas    1000      30  2017-10-03
10     11   Dennis   41000      30  2024-01-05
11     12    Karan    2200      20  2018-06-16
12     13   Simran    1500      10  2019-12-19
13     14     Amit    2000      30  2022-04-09
14     15     Neha    1700      20  2021-07-22
15     16    Rahul    1200      10  2016-03-28
16     17    Divya    3000      30  2015-11-11
17     18   Rakesh    1800      10  2020-09-04
18     19   Monica    2500      20  2023-08-07
19     20     John    2300      30  2018-10-29
20     21    Sneha    2700      10  2022-12-14
21     22    David    1000      20  2017-02-17
22     23    Anita    1500      30  2019-05-21
23     24    Vinod    1800      10  2016-07-30
24     25    Meena    2000      20  2020-03-13
25     26    Harsh    1600      10  2021-09-25
26     27   Kavita    1400      30  2019-01-06
27     28    Mohan    1300      10  2015-04-17
28     29    Priya    1200      20  2023-02-11
29     30   Suresh    1100      10  2018-09-09
30     31     Rani    1900      20  2022-11-03
31     32     Ajay    2100      10  2020-06-26
32     33    Nidhi    2400      30  2016-05-12
33     34    Vivek    2000      20  2017-07-31
34     35    Seema    3000      10  2021-10-15
35     36     Ritu    3200      20  2023-05-01
36     37    Kunal    2800      30  2015-08-22
37     38     Alok    2700      10  2019-03-02
38     39   Poonam    2600      20  2022-02-05
39     40     Yash    2500      30  2020-07-19
40     41     Nina    2300      20  2018-12-28
41     42    Tarun    2200      10  2021-01-09
42     43    Geeta    2100      30  2017-11-14
43     44    Ashok    1900      10  2016-06-08
44     45  Sanjana    1800      20  2023-03-17
45     46    Manoj    1700      30  2019-07-24
46     47    Payal    1600      20  2015-10-10

In [32]:
 df_agg = df.groupby(['deptno','salary'])['salary'].agg(['sum','max','min','count'])

                 sum    max    min  count
deptno salary
10     1000     4000   1000   1000      4
       1100     1100   1100   1100      1
       1200     1200   1200   1200      1
       1300     1300   1300   1300      1
       1500     1500   1500   1500      1
       1600     1600   1600   1600      1
       1800     3600   1800   1800      2
       1900     1900   1900   1900      1
       2000     2000   2000   2000      1
       2100     2100   2100   2100      1
       2200     2200   2200   2200      1
       2700     5400   2700   2700      2
       3000     3000   3000   3000      1
20     1000     2000   1000   1000      2
       1200     1200   1200   1200      1
       1600     1600   1600   1600      1
       1700     1700   1700   1700      1
       1800     1800   1800   1800      1
       1900     1900   1900   1900      1
       2000     4000   2000   2000      2
       2200     2200   2200   2200      1
       2300     2300   2300   2300      1
       2500     2500   2500   2500      1
       2600     2600   2600   2600      1
       3000     3000   3000   3000      1
       3200     3200   3200   3200      1
30     1000     2000   1000   1000      2
       1400     1400   1400   1400      1
       1500     1500   1500   1500      1
       1700     1700   1700   1700      1
       2000     2000   2000   2000      1
       2100     2100   2100   2100      1
       2300     2300   2300   2300      1
       2400     2400   2400   2400      1
       2500     2500   2500   2500      1
       2800     2800   2800   2800      1
       3000     3000   3000   3000      1
       4000     4000   4000   4000      1
       41000   41000  41000  41000      1

In [33]:
 df= df.sort_values(by=['salary'])

In [34]:
df

      eno    ename  salary  deptno         doj
0      10    Amber    1000      10  2018-05-14
1       2     Amar    1000      10  2017-03-22
2       8    Sagar    1000      20  2020-11-30
3       4   Thomas    1000      10  2019-08-18
5       6    Smith    1000      10  2016-12-01
7       3     Nick    1000      30  2015-09-15
9       1    Vikas    1000      30  2017-10-03
21     22    David    1000      20  2017-02-17
29     30   Suresh    1100      10  2018-09-09
28     29    Priya    1200      20  2023-02-11
15     16    Rahul    1200      10  2016-03-28
27     28    Mohan    1300      10  2015-04-17
26     27   Kavita    1400      30  2019-01-06
12     13   Simran    1500      10  2019-12-19
22     23    Anita    1500      30  2019-05-21
25     26    Harsh    1600      10  2021-09-25
46     47    Payal    1600      20  2015-10-10
14     15     Neha    1700      20  2021-07-22
45     46    Manoj    1700      30  2019-07-24
17     18   Rakesh    1800      10  2020-09-04
23     24    Vinod    1800      10  2016-07-30
44     45  Sanjana    1800      20  2023-03-17
43     44    Ashok    1900      10  2016-06-08
30     31     Rani    1900      20  2022-11-03
4       5     Jade    2000      10  2021-02-10
13     14     Amit    2000      30  2022-04-09
24     25    Meena    2000      20  2020-03-13
33     34    Vivek    2000      20  2017-07-31
42     43    Geeta    2100      30  2017-11-14
31     32     Ajay    2100      10  2020-06-26
11     12    Karan    2200      20  2018-06-16
41     42    Tarun    2200      10  2021-01-09
19     20     John    2300      30  2018-10-29
40     41     Nina    2300      20  2018-12-28
32     33    Nidhi    2400      30  2016-05-12
39     40     Yash    2500      30  2020-07-19
18     19   Monica    2500      20  2023-08-07
38     39   Poonam    2600      20  2022-02-05
20     21    Sneha    2700      10  2022-12-14
37     38     Alok    2700      10  2019-03-02
36     37    Kunal    2800      30  2015-08-22
34     35    Seema    3000      10  2021-10-15
16     17    Divya    3000      30  2015-11-11
6       7   Robert    3000      20  2023-06-25
35     36     Ritu    3200      20  2023-05-01
8       9    Naman    4000      30  2020-01-20
10     11   Dennis   41000      30  2024-01-05

In [35]:
df= df.sort_values(by=['salary','deptno'])

In [36]:
df

      eno    ename  salary  deptno         doj
0      10    Amber    1000      10  2018-05-14
1       2     Amar    1000      10  2017-03-22
3       4   Thomas    1000      10  2019-08-18
5       6    Smith    1000      10  2016-12-01
2       8    Sagar    1000      20  2020-11-30
21     22    David    1000      20  2017-02-17
7       3     Nick    1000      30  2015-09-15
9       1    Vikas    1000      30  2017-10-03
29     30   Suresh    1100      10  2018-09-09
15     16    Rahul    1200      10  2016-03-28
28     29    Priya    1200      20  2023-02-11
27     28    Mohan    1300      10  2015-04-17
26     27   Kavita    1400      30  2019-01-06
12     13   Simran    1500      10  2019-12-19
22     23    Anita    1500      30  2019-05-21
25     26    Harsh    1600      10  2021-09-25
46     47    Payal    1600      20  2015-10-10
14     15     Neha    1700      20  2021-07-22
45     46    Manoj    1700      30  2019-07-24
17     18   Rakesh    1800      10  2020-09-04
23     24    Vinod    1800      10  2016-07-30
44     45  Sanjana    1800      20  2023-03-17
43     44    Ashok    1900      10  2016-06-08
30     31     Rani    1900      20  2022-11-03
4       5     Jade    2000      10  2021-02-10
24     25    Meena    2000      20  2020-03-13
33     34    Vivek    2000      20  2017-07-31
13     14     Amit    2000      30  2022-04-09
31     32     Ajay    2100      10  2020-06-26
42     43    Geeta    2100      30  2017-11-14
41     42    Tarun    2200      10  2021-01-09
11     12    Karan    2200      20  2018-06-16
40     41     Nina    2300      20  2018-12-28
19     20     John    2300      30  2018-10-29
32     33    Nidhi    2400      30  2016-05-12
18     19   Monica    2500      20  2023-08-07
39     40     Yash    2500      30  2020-07-19
38     39   Poonam    2600      20  2022-02-05
20     21    Sneha    2700      10  2022-12-14
37     38     Alok    2700      10  2019-03-02
36     37    Kunal    2800      30  2015-08-22
34     35    Seema    3000      10  2021-10-15
6       7   Robert    3000      20  2023-06-25
16     17    Divya    3000      30  2015-11-11
35     36     Ritu    3200      20  2023-05-01
8       9    Naman    4000      30  2020-01-20
10     11   Dennis   41000      30  2024-01-05

In [40]:
 df= df.sort_values(by=['salary','deptno'],ascending=[True,True])

In [41]:
df

      eno    ename  salary  deptno         doj
0      10    Amber    1000      10  2018-05-14
1       2     Amar    1000      10  2017-03-22
3       4   Thomas    1000      10  2019-08-18
5       6    Smith    1000      10  2016-12-01
2       8    Sagar    1000      20  2020-11-30
21     22    David    1000      20  2017-02-17
7       3     Nick    1000      30  2015-09-15
9       1    Vikas    1000      30  2017-10-03
29     30   Suresh    1100      10  2018-09-09
15     16    Rahul    1200      10  2016-03-28
28     29    Priya    1200      20  2023-02-11
27     28    Mohan    1300      10  2015-04-17
26     27   Kavita    1400      30  2019-01-06
12     13   Simran    1500      10  2019-12-19
22     23    Anita    1500      30  2019-05-21
25     26    Harsh    1600      10  2021-09-25
46     47    Payal    1600      20  2015-10-10
14     15     Neha    1700      20  2021-07-22
45     46    Manoj    1700      30  2019-07-24
17     18   Rakesh    1800      10  2020-09-04
23     24    Vinod    1800      10  2016-07-30
44     45  Sanjana    1800      20  2023-03-17
43     44    Ashok    1900      10  2016-06-08
30     31     Rani    1900      20  2022-11-03
4       5     Jade    2000      10  2021-02-10
24     25    Meena    2000      20  2020-03-13
33     34    Vivek    2000      20  2017-07-31
13     14     Amit    2000      30  2022-04-09
31     32     Ajay    2100      10  2020-06-26
42     43    Geeta    2100      30  2017-11-14
41     42    Tarun    2200      10  2021-01-09
11     12    Karan    2200      20  2018-06-16
40     41     Nina    2300      20  2018-12-28
19     20     John    2300      30  2018-10-29
32     33    Nidhi    2400      30  2016-05-12
18     19   Monica    2500      20  2023-08-07
39     40     Yash    2500      30  2020-07-19
38     39   Poonam    2600      20  2022-02-05
20     21    Sneha    2700      10  2022-12-14
37     38     Alok    2700      10  2019-03-02
36     37    Kunal    2800      30  2015-08-22
34     35    Seema    3000      10  2021-10-15
6       7   Robert    3000      20  2023-06-25
16     17    Divya    3000      30  2015-11-11
35     36     Ritu    3200      20  2023-05-01
8       9    Naman    4000      30  2020-01-20
10     11   Dennis   41000      30  2024-01-05

In [42]:
df=  df.sort_values(by=['salary','deptno'],ascending=[True,False])

In [43]:
df

      eno    ename  salary  deptno         doj
7       3     Nick    1000      30  2015-09-15
9       1    Vikas    1000      30  2017-10-03
2       8    Sagar    1000      20  2020-11-30
21     22    David    1000      20  2017-02-17
0      10    Amber    1000      10  2018-05-14
1       2     Amar    1000      10  2017-03-22
3       4   Thomas    1000      10  2019-08-18
5       6    Smith    1000      10  2016-12-01
29     30   Suresh    1100      10  2018-09-09
28     29    Priya    1200      20  2023-02-11
15     16    Rahul    1200      10  2016-03-28
27     28    Mohan    1300      10  2015-04-17
26     27   Kavita    1400      30  2019-01-06
22     23    Anita    1500      30  2019-05-21
12     13   Simran    1500      10  2019-12-19
46     47    Payal    1600      20  2015-10-10
25     26    Harsh    1600      10  2021-09-25
45     46    Manoj    1700      30  2019-07-24
14     15     Neha    1700      20  2021-07-22
44     45  Sanjana    1800      20  2023-03-17
17     18   Rakesh    1800      10  2020-09-04
23     24    Vinod    1800      10  2016-07-30
30     31     Rani    1900      20  2022-11-03
43     44    Ashok    1900      10  2016-06-08
13     14     Amit    2000      30  2022-04-09
24     25    Meena    2000      20  2020-03-13
33     34    Vivek    2000      20  2017-07-31
4       5     Jade    2000      10  2021-02-10
42     43    Geeta    2100      30  2017-11-14
31     32     Ajay    2100      10  2020-06-26
11     12    Karan    2200      20  2018-06-16
41     42    Tarun    2200      10  2021-01-09
19     20     John    2300      30  2018-10-29
40     41     Nina    2300      20  2018-12-28
32     33    Nidhi    2400      30  2016-05-12
39     40     Yash    2500      30  2020-07-19
18     19   Monica    2500      20  2023-08-07
38     39   Poonam    2600      20  2022-02-05
20     21    Sneha    2700      10  2022-12-14
37     38     Alok    2700      10  2019-03-02
36     37    Kunal    2800      30  2015-08-22
16     17    Divya    3000      30  2015-11-11
6       7   Robert    3000      20  2023-06-25
34     35    Seema    3000      10  2021-10-15
35     36     Ritu    3200      20  2023-05-01
8       9    Naman    4000      30  2020-01-20
10     11   Dennis   41000      30  2024-01-05

In [45]:
 import pandas as pd

In [47]:
 df = pd.read_csv("emp.csv")

In [48]:
df

      eno    ename  salary  deptno         doj
0      10    Amber    1000      10  2018-05-14
1       2     Amar    1000      10  2017-03-22
2       8    Sagar    1000      20  2020-11-30
3       4   Thomas    1000      10  2019-08-18
4       5     Jade    2000      10  2021-02-10
5       6    Smith    1000      10  2016-12-01
6       7   Robert    3000      20  2023-06-25
7       3     Nick    1000      30  2015-09-15
8       9    Naman    4000      30  2020-01-20
9       1    Vikas    1000      30  2017-10-03
10     11   Dennis   41000      30  2024-01-05
11     12    Karan    2200      20  2018-06-16
12     13   Simran    1500      10  2019-12-19
13     14     Amit    2000      30  2022-04-09
14     15     Neha    1700      20  2021-07-22
15     16    Rahul    1200      10  2016-03-28
16     17    Divya    3000      30  2015-11-11
17     18   Rakesh    1800      10  2020-09-04
18     19   Monica    2500      20  2023-08-07
19     20     John    2300      30  2018-10-29
20     21    Sneha    2700      10  2022-12-14
21     22    David    1000      20  2017-02-17
22     23    Anita    1500      30  2019-05-21
23     24    Vinod    1800      10  2016-07-30
24     25    Meena    2000      20  2020-03-13
25     26    Harsh    1600      10  2021-09-25
26     27   Kavita    1400      30  2019-01-06
27     28    Mohan    1300      10  2015-04-17
28     29    Priya    1200      20  2023-02-11
29     30   Suresh    1100      10  2018-09-09
30     31     Rani    1900      20  2022-11-03
31     32     Ajay    2100      10  2020-06-26
32     33    Nidhi    2400      30  2016-05-12
33     34    Vivek    2000      20  2017-07-31
34     35    Seema    3000      10  2021-10-15
35     36     Ritu    3200      20  2023-05-01
36     37    Kunal    2800      30  2015-08-22
37     38     Alok    2700      10  2019-03-02
38     39   Poonam    2600      20  2022-02-05
39     40     Yash    2500      30  2020-07-19
40     41     Nina    2300      20  2018-12-28
41     42    Tarun    2200      10  2021-01-09
42     43    Geeta    2100      30  2017-11-14
43     44    Ashok    1900      10  2016-06-08
44     45  Sanjana    1800      20  2023-03-17
45     46    Manoj    1700      30  2019-07-24
46     47    Payal    1600      20  2015-10-10

In [50]:
  df.sort_index(ascending = True)

      eno    ename  salary  deptno         doj
0      10    Amber    1000      10  2018-05-14
1       2     Amar    1000      10  2017-03-22
2       8    Sagar    1000      20  2020-11-30
3       4   Thomas    1000      10  2019-08-18
4       5     Jade    2000      10  2021-02-10
5       6    Smith    1000      10  2016-12-01
6       7   Robert    3000      20  2023-06-25
7       3     Nick    1000      30  2015-09-15
8       9    Naman    4000      30  2020-01-20
9       1    Vikas    1000      30  2017-10-03
10     11   Dennis   41000      30  2024-01-05
11     12    Karan    2200      20  2018-06-16
12     13   Simran    1500      10  2019-12-19
13     14     Amit    2000      30  2022-04-09
14     15     Neha    1700      20  2021-07-22
15     16    Rahul    1200      10  2016-03-28
16     17    Divya    3000      30  2015-11-11
17     18   Rakesh    1800      10  2020-09-04
18     19   Monica    2500      20  2023-08-07
19     20     John    2300      30  2018-10-29
20     21    Sneha    2700      10  2022-12-14
21     22    David    1000      20  2017-02-17
22     23    Anita    1500      30  2019-05-21
23     24    Vinod    1800      10  2016-07-30
24     25    Meena    2000      20  2020-03-13
25     26    Harsh    1600      10  2021-09-25
26     27   Kavita    1400      30  2019-01-06
27     28    Mohan    1300      10  2015-04-17
28     29    Priya    1200      20  2023-02-11
29     30   Suresh    1100      10  2018-09-09
30     31     Rani    1900      20  2022-11-03
31     32     Ajay    2100      10  2020-06-26
32     33    Nidhi    2400      30  2016-05-12
33     34    Vivek    2000      20  2017-07-31
34     35    Seema    3000      10  2021-10-15
35     36     Ritu    3200      20  2023-05-01
36     37    Kunal    2800      30  2015-08-22
37     38     Alok    2700      10  2019-03-02
38     39   Poonam    2600      20  2022-02-05
39     40     Yash    2500      30  2020-07-19
40     41     Nina    2300      20  2018-12-28
41     42    Tarun    2200      10  2021-01-09
42     43    Geeta    2100      30  2017-11-14
43     44    Ashok    1900      10  2016-06-08
44     45  Sanjana    1800      20  2023-03-17
45     46    Manoj    1700      30  2019-07-24
46     47    Payal    1600      20  2015-10-10

In [51]:
 df.sort_index(ascending=False)

      eno    ename  salary  deptno         doj
46     47    Payal    1600      20  2015-10-10
45     46    Manoj    1700      30  2019-07-24
44     45  Sanjana    1800      20  2023-03-17
43     44    Ashok    1900      10  2016-06-08
42     43    Geeta    2100      30  2017-11-14
41     42    Tarun    2200      10  2021-01-09
40     41     Nina    2300      20  2018-12-28
39     40     Yash    2500      30  2020-07-19
38     39   Poonam    2600      20  2022-02-05
37     38     Alok    2700      10  2019-03-02
36     37    Kunal    2800      30  2015-08-22
35     36     Ritu    3200      20  2023-05-01
34     35    Seema    3000      10  2021-10-15
33     34    Vivek    2000      20  2017-07-31
32     33    Nidhi    2400      30  2016-05-12
31     32     Ajay    2100      10  2020-06-26
30     31     Rani    1900      20  2022-11-03
29     30   Suresh    1100      10  2018-09-09
28     29    Priya    1200      20  2023-02-11
27     28    Mohan    1300      10  2015-04-17
26     27   Kavita    1400      30  2019-01-06
25     26    Harsh    1600      10  2021-09-25
24     25    Meena    2000      20  2020-03-13
23     24    Vinod    1800      10  2016-07-30
22     23    Anita    1500      30  2019-05-21
21     22    David    1000      20  2017-02-17
20     21    Sneha    2700      10  2022-12-14
19     20     John    2300      30  2018-10-29
18     19   Monica    2500      20  2023-08-07
17     18   Rakesh    1800      10  2020-09-04
16     17    Divya    3000      30  2015-11-11
15     16    Rahul    1200      10  2016-03-28
14     15     Neha    1700      20  2021-07-22
13     14     Amit    2000      30  2022-04-09
12     13   Simran    1500      10  2019-12-19
11     12    Karan    2200      20  2018-06-16
10     11   Dennis   41000      30  2024-01-05
9       1    Vikas    1000      30  2017-10-03
8       9    Naman    4000      30  2020-01-20
7       3     Nick    1000      30  2015-09-15
6       7   Robert    3000      20  2023-06-25
5       6    Smith    1000      10  2016-12-01
4       5     Jade    2000      10  2021-02-10
3       4   Thomas    1000      10  2019-08-18
2       8    Sagar    1000      20  2020-11-30
1       2     Amar    1000      10  2017-03-22
0      10    Amber    1000      10  2018-05-14

In [58]:
 emp_count_by_deptno = df.groupby('deptno')['ename'].count().reset_index()

In [55]:
df = pd.DataFrame('emp.csv')

ValueError: DataFrame constructor not properly called!

In [56]:
df = pd.read_csv("emp.csv")

In [60]:
emp_count_by_deptno = df.groupby('deptno')['ename'].count().reset_index()

In [61]:
emp_count_by_deptno

   deptno  ename
0      10     18
1      20     15
2      30     14

In [62]:
filtered_df = df[df['salary'] < 10000]

In [63]:
filtered_df

      eno    ename  salary  deptno         doj
0      10    Amber    1000      10  2018-05-14
1       2     Amar    1000      10  2017-03-22
2       8    Sagar    1000      20  2020-11-30
3       4   Thomas    1000      10  2019-08-18
4       5     Jade    2000      10  2021-02-10
5       6    Smith    1000      10  2016-12-01
6       7   Robert    3000      20  2023-06-25
7       3     Nick    1000      30  2015-09-15
8       9    Naman    4000      30  2020-01-20
9       1    Vikas    1000      30  2017-10-03
11     12    Karan    2200      20  2018-06-16
12     13   Simran    1500      10  2019-12-19
13     14     Amit    2000      30  2022-04-09
14     15     Neha    1700      20  2021-07-22
15     16    Rahul    1200      10  2016-03-28
16     17    Divya    3000      30  2015-11-11
17     18   Rakesh    1800      10  2020-09-04
18     19   Monica    2500      20  2023-08-07
19     20     John    2300      30  2018-10-29
20     21    Sneha    2700      10  2022-12-14
21     22    David    1000      20  2017-02-17
22     23    Anita    1500      30  2019-05-21
23     24    Vinod    1800      10  2016-07-30
24     25    Meena    2000      20  2020-03-13
25     26    Harsh    1600      10  2021-09-25
26     27   Kavita    1400      30  2019-01-06
27     28    Mohan    1300      10  2015-04-17
28     29    Priya    1200      20  2023-02-11
29     30   Suresh    1100      10  2018-09-09
30     31     Rani    1900      20  2022-11-03
31     32     Ajay    2100      10  2020-06-26
32     33    Nidhi    2400      30  2016-05-12
33     34    Vivek    2000      20  2017-07-31
34     35    Seema    3000      10  2021-10-15
35     36     Ritu    3200      20  2023-05-01
36     37    Kunal    2800      30  2015-08-22
37     38     Alok    2700      10  2019-03-02
38     39   Poonam    2600      20  2022-02-05
39     40     Yash    2500      30  2020-07-19
40     41     Nina    2300      20  2018-12-28
41     42    Tarun    2200      10  2021-01-09
42     43    Geeta    2100      30  2017-11-14
43     44    Ashok    1900      10  2016-06-08
44     45  Sanjana    1800      20  2023-03-17
45     46    Manoj    1700      30  2019-07-24
46     47    Payal    1600      20  2015-10-10

In [64]:
 total_saalries_by_deptno_salLessThan10000 = filtered_df.groupby('deptno')
 ['salary'].sum().reset_index()

AttributeError: 'list' object has no attribute 'sum'

In [1]:
 Filtered_df = (df['deptno'] == 10) | (df['deptno'] == 20)

NameError: name 'df' is not defined

In [2]:
df = pd.read_csv("emp.csv")

NameError: name 'pd' is not defined

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("emp.csv")

In [5]:
df

      eno    ename  salary  deptno         doj
0      10    Amber    1000      10  2018-05-14
1       2     Amar    1000      10  2017-03-22
2       8    Sagar    1000      20  2020-11-30
3       4   Thomas    1000      10  2019-08-18
4       5     Jade    2000      10  2021-02-10
5       6    Smith    1000      10  2016-12-01
6       7   Robert    3000      20  2023-06-25
7       3     Nick    1000      30  2015-09-15
8       9    Naman    4000      30  2020-01-20
9       1    Vikas    1000      30  2017-10-03
10     11   Dennis   41000      30  2024-01-05
11     12    Karan    2200      20  2018-06-16
12     13   Simran    1500      10  2019-12-19
13     14     Amit    2000      30  2022-04-09
14     15     Neha    1700      20  2021-07-22
15     16    Rahul    1200      10  2016-03-28
16     17    Divya    3000      30  2015-11-11
17     18   Rakesh    1800      10  2020-09-04
18     19   Monica    2500      20  2023-08-07
19     20     John    2300      30  2018-10-29
20     21    Sneha    2700      10  2022-12-14
21     22    David    1000      20  2017-02-17
22     23    Anita    1500      30  2019-05-21
23     24    Vinod    1800      10  2016-07-30
24     25    Meena    2000      20  2020-03-13
25     26    Harsh    1600      10  2021-09-25
26     27   Kavita    1400      30  2019-01-06
27     28    Mohan    1300      10  2015-04-17
28     29    Priya    1200      20  2023-02-11
29     30   Suresh    1100      10  2018-09-09
30     31     Rani    1900      20  2022-11-03
31     32     Ajay    2100      10  2020-06-26
32     33    Nidhi    2400      30  2016-05-12
33     34    Vivek    2000      20  2017-07-31
34     35    Seema    3000      10  2021-10-15
35     36     Ritu    3200      20  2023-05-01
36     37    Kunal    2800      30  2015-08-22
37     38     Alok    2700      10  2019-03-02
38     39   Poonam    2600      20  2022-02-05
39     40     Yash    2500      30  2020-07-19
40     41     Nina    2300      20  2018-12-28
41     42    Tarun    2200      10  2021-01-09
42     43    Geeta    2100      30  2017-11-14
43     44    Ashok    1900      10  2016-06-08
44     45  Sanjana    1800      20  2023-03-17
45     46    Manoj    1700      30  2019-07-24
46     47    Payal    1600      20  2015-10-10

In [13]:
 Filtered_df = (df['deptno'] == 10) | (df['deptno'] == 20)

In [15]:
from sqlalchemy import create_engine
import pandas as pd

oracle_connection = create_engine( "oracle+cx_oracle://sys:Admin@localhost:1521/orcl?mode=SYSDBA")
sql_query = """select *from emp"""
df1 = pd.read_sql(sql_query,oracle_connection)

In [16]:
df1

    empno   ename        job     mgr   hiredate     sal    comm  deptno
0    7839    KING  PRESIDENT     NaN 1981-11-17  5000.0     NaN      10
1    7698   BLAKE    MANAGER  7839.0 1981-05-01  2850.0     NaN      30
2    7782   CLARK    MANAGER  7839.0 1981-06-09  2450.0     NaN      10
3    7566   JONES    MANAGER  7839.0 1981-04-02  2975.0     NaN      20
4    7788   SCOTT    ANALYST  7566.0 1987-04-19  3000.0     NaN      20
5    7902    FORD    ANALYST  7566.0 1981-12-03  3000.0     NaN      20
6    7369   SMITH      CLERK  7902.0 1980-12-17   800.0     NaN      20
7    7499   ALLEN   SALESMAN  7698.0 1981-02-20  1600.0   300.0      30
8    7521    WARD   SALESMAN  7698.0 1981-02-22  1250.0   500.0      30
9    7654  MARTIN   SALESMAN  7698.0 1981-09-28  1250.0  1400.0      30
10   7844  TURNER   SALESMAN  7698.0 1981-09-08  1500.0     0.0      30
11   7876   ADAMS      CLERK  7788.0 1987-05-23  1100.0     NaN      20
12   7900   JAMES      CLERK  7698.0 1981-12-03   950.0     NaN      30
13   7934  MILLER      CLERK  7782.0 1982-01-23  1300.0     NaN      10

In [17]:
df2 = pd.read_csv("emp.csv")

In [18]:
df2

      eno    ename  salary  deptno         doj
0      10    Amber    1000      10  2018-05-14
1       2     Amar    1000      10  2017-03-22
2       8    Sagar    1000      20  2020-11-30
3       4   Thomas    1000      10  2019-08-18
4       5     Jade    2000      10  2021-02-10
5       6    Smith    1000      10  2016-12-01
6       7   Robert    3000      20  2023-06-25
7       3     Nick    1000      30  2015-09-15
8       9    Naman    4000      30  2020-01-20
9       1    Vikas    1000      30  2017-10-03
10     11   Dennis   41000      30  2024-01-05
11     12    Karan    2200      20  2018-06-16
12     13   Simran    1500      10  2019-12-19
13     14     Amit    2000      30  2022-04-09
14     15     Neha    1700      20  2021-07-22
15     16    Rahul    1200      10  2016-03-28
16     17    Divya    3000      30  2015-11-11
17     18   Rakesh    1800      10  2020-09-04
18     19   Monica    2500      20  2023-08-07
19     20     John    2300      30  2018-10-29
20     21    Sneha    2700      10  2022-12-14
21     22    David    1000      20  2017-02-17
22     23    Anita    1500      30  2019-05-21
23     24    Vinod    1800      10  2016-07-30
24     25    Meena    2000      20  2020-03-13
25     26    Harsh    1600      10  2021-09-25
26     27   Kavita    1400      30  2019-01-06
27     28    Mohan    1300      10  2015-04-17
28     29    Priya    1200      20  2023-02-11
29     30   Suresh    1100      10  2018-09-09
30     31     Rani    1900      20  2022-11-03
31     32     Ajay    2100      10  2020-06-26
32     33    Nidhi    2400      30  2016-05-12
33     34    Vivek    2000      20  2017-07-31
34     35    Seema    3000      10  2021-10-15
35     36     Ritu    3200      20  2023-05-01
36     37    Kunal    2800      30  2015-08-22
37     38     Alok    2700      10  2019-03-02
38     39   Poonam    2600      20  2022-02-05
39     40     Yash    2500      30  2020-07-19
40     41     Nina    2300      20  2018-12-28
41     42    Tarun    2200      10  2021-01-09
42     43    Geeta    2100      30  2017-11-14
43     44    Ashok    1900      10  2016-06-08
44     45  Sanjana    1800      20  2023-03-17
45     46    Manoj    1700      30  2019-07-24
46     47    Payal    1600      20  2015-10-10

In [19]:
df1

    empno   ename        job     mgr   hiredate     sal    comm  deptno
0    7839    KING  PRESIDENT     NaN 1981-11-17  5000.0     NaN      10
1    7698   BLAKE    MANAGER  7839.0 1981-05-01  2850.0     NaN      30
2    7782   CLARK    MANAGER  7839.0 1981-06-09  2450.0     NaN      10
3    7566   JONES    MANAGER  7839.0 1981-04-02  2975.0     NaN      20
4    7788   SCOTT    ANALYST  7566.0 1987-04-19  3000.0     NaN      20
5    7902    FORD    ANALYST  7566.0 1981-12-03  3000.0     NaN      20
6    7369   SMITH      CLERK  7902.0 1980-12-17   800.0     NaN      20
7    7499   ALLEN   SALESMAN  7698.0 1981-02-20  1600.0   300.0      30
8    7521    WARD   SALESMAN  7698.0 1981-02-22  1250.0   500.0      30
9    7654  MARTIN   SALESMAN  7698.0 1981-09-28  1250.0  1400.0      30
10   7844  TURNER   SALESMAN  7698.0 1981-09-08  1500.0     0.0      30
11   7876   ADAMS      CLERK  7788.0 1987-05-23  1100.0     NaN      20
12   7900   JAMES      CLERK  7698.0 1981-12-03   950.0     NaN      30
13   7934  MILLER      CLERK  7782.0 1982-01-23  1300.0     NaN      10

In [20]:
 df1.merge(df2,on='deptno',how='inner')

,empno,ename_x,job,mgr,hiredate,sal,comm,deptno,eno,ename_y,salary,doj
0,7839,KING,PRESIDENT,NaN,1981-11-17,5000.0,NaN,10,10,Amber,1000,2018-05-14
1,7839,KING,PRESIDENT,NaN,1981-11-17,5000.0,NaN,10,2,Amar,1000,2017-03-22
2,7839,KING,PRESIDENT,NaN,1981-11-17,5000.0,NaN,10,4,Thomas,1000,2019-08-18
3,7839,KING,PRESIDENT,NaN,1981-11-17,5000.0,NaN,10,5,Jade,2000,2021-02-10
4,7839,KING,PRESIDENT,NaN,1981-11-17,5000.0,NaN,10,6,Smith,1000,2016-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...
208,7934,MILLER,CLERK,7782.0,1982-01-23,1300.0,NaN,10,32,Ajay,2100,2020-06-26
209,7934,MILLER,CLERK,7782.0,1982-01-23,1300.0,NaN,10,35,Seema,3000,2021-10-15
210,7934,MILLER,CLERK,7782.0,1982-01-23,1300.0,NaN,10,38,Alok,2700,2019-03-02
211,7934,MILLER,CLERK,7782.0,1982-01-23,1300.0,NaN,10,42,Tarun,2200,2021-01-09
212,7934,MILLER,CLERK,7782.0,1982-01-23,1300.0,NaN,10,44,Ashok,1900,2016-06-08